//! Stands in for the `verum` crate.
//!
//! Deliberately tiny. The question under test is Rust visibility and how sqlx's
//! macros expand, neither of which needs cons lists, `Ctx`, or capability
//! checking to reproduce. Adding them would only make the probes harder to read.

/// Marker only, so the app's `User` is a Domain in the sense the specs use.
pub trait Domain {}

/// The Repr conversion expressed as a **framework trait**.
///
/// This is NOT the shape `docs/specs/persistence.md` currently specifies — that
/// one uses inherent `pub(crate) fn from_repr` / `as_repr`. It is here because
/// "put the conversion behind a verum trait" is one of the alternatives #18 will
/// have to weigh, and P9/P10 measure what it costs before anyone picks it.
///
/// The cost is structural: **a trait method cannot be `pub(crate)`**. It is
/// exactly as public as the trait, so this makes the conversion reachable from
/// every crate rather than one, and `Self::Repr` becomes nameable by projection
/// even where the underlying type is not.
pub trait DomainRepr: Sized {
    type Repr;
    fn from_repr(r: Self::Repr) -> Self;
    fn as_repr(&self) -> &Self::Repr;
}

// ---------------------------------------------------------------------------
// #33 — the candidate gates. Each of the three below is measured to FAIL; they
// are kept because "no trait-bound gate closes path 21" is a claim, and a claim
// in this project needs the counterexample compiled rather than argued.
// ---------------------------------------------------------------------------

/// A capability token: no public constructor, so only `fw` can mint one.
///
/// The idea under test is that `from_repr` takes one, making "you may build a
/// Domain" a thing the type system carries. P22/P23 measure what it is worth.
pub struct RepoToken(());

/// The trait `fw` hands a freshly minted token to.
pub trait TokenRepository {
    type Domain;
    fn load(&self, t: RepoToken) -> Self::Domain;
}

/// The only place a `RepoToken` is created. Mirrors what the runtime would do.
pub fn run_repository<R: TokenRepository>(r: &R) -> R::Domain {
    r.load(RepoToken(()))
}

/// The second candidate: express the permission as a **bound** rather than a
/// value, so the rejection is `E0277` and can carry Verum's own wording.
///
/// P24/P25 measure why this does not hold: the trait is not sealed, so
/// `impl fw::RepositoryProof for MyProof {}` is a foreign trait on a local type
/// — which the orphan rules allow from *any* crate. Sealing it is not available
/// either, because `#[derive(Domain)]` expands inside the user's crate, so
/// whatever the expansion writes to satisfy a seal, a human can write too.
#[diagnostic::on_unimplemented(
    message = "`{Self}` cannot authorise constructing a Domain value",
    note = "Only the Repository generated by `#[derive(Domain)]` may build this Domain from its Repr. Load it through that repository rather than calling `from_repr` yourself."
)]
pub trait RepositoryProof {}
